version: '3'
services:
  couchdb:
    image: "couchdb:latest" 
    hostname: couchdb
    environment:
      COUCHDB_USER: ${DBUSER}
      COUCHDB_PASSWORD: ${DBPASSWORD}
    volumes:
      - couchdb-data:/opt/couchdb/data
  esp-backend:
    # image: "esp-backend:latest"
    build:
      context: src/
      dockerfile: backend/Dockerfile
    ports:
      - 8080:80
    links:
      - couchdb
    environment:
      ASPNETCORE_ENVIRONMENT: production
      COUCHDB__USERNAME: ${DBUSER}
      COUCHDB__PASSWORD: ${DBPASSWORD}
      COUCHDB__HOST: couchdb
      COUCHDB__PORT: ${DBPORT}
      COUCHDB__DEVICES: devices
      COUCHDB__ORGANIZATIONS: organizations

  portal-backend:
    # image: "portal-backend:latest"
    build:
      context: src/
      dockerfile: portal/Dockerfile
    ports:
      - 8081:80
    links:
      - couchdb
    environment:
      ASPNETCORE_ENVIRONMENT: production
      COUCHDB__USERNAME: ${DBUSER}
      COUCHDB__PASSWORD: ${DBPASSWORD}
      COUCHDB__HOST: couchdb
      COUCHDB__PORT: ${DBPORT}
      COUCHDB__DEVICES: devices
      COUCHDB__ORGANIZATIONS: organizations

volumes:
  couchdb-data:
    external: true
